var data = [
  {
    "nombre": "Stygimoloch", "contenido": [
      { "titulo": "Origen", "informacion": "Stygimoloch (gr.'diablo espinoso del río Estigia') es un género representado por una única especie de dinosaurio marginocéfalo paquicefalosáurido, que vivió en el Cretácico superior hace aproximadamente 66 millones de años, en el Maastrichtiense, en lo que hoy es Norteamérica. Es conocido de las Formaciones Hell Creek y Lance en el oeste de Estados Unidos, viviendo junto a Tyrannosaurus y Triceratops." },
      { "titulo": "Descripción Pt.1", "informacion": "Se cree que Stygimoloch vivía en manadas. Tenía las patas delanteras cortas y las traseras largas, y una cola larga para mantener el equilibrio. Poseía en la cabeza unos cuernos que le servían para impresionar. Su cráneo tenía un espesor de unos 25 centímetros. Medía alrededor de 3 metros de longitud y 2 de altura. Tenía 4 dedos en las extremidades delanteras y los pies. Era un paquicefalosáurido relativamente grande, con el cráneo midiendo cerca de 46 centímetros de largo. Entre los paquicefalosáuridos norteamericanos, solamente Pachycephalosaurus era más grande. A diferencia de otros paquicefalosáuridos, el cráneo abovedado era relativamente pequeño, aplanado levemente de lado a lado, y en forma de pera; incluso cuando está aislada, esta bóveda inusual puede fácilmente ser distinguida de las bóvedas más anchas y grandes de Pachycephalosaurus." },
      { "titulo": "Descripción Pt.2", "informacion": "Mientras que la bóveda se reduce en tamaño, la ornamentación en el cráneo es más elaborada que en cualquier otro paquicefalosáurido. Cuernos cortos y cónicos cubrieron la nariz, y en las esquinas traseras del cráneo tenían un par de enormes y masivos cuernos, apuntando hacia atrás, de hasta 5 centímetros de diámetro y 15 centímetros de largo, rodeados por dos o tres puntos más pequeños. La función de esta ornamentación inusual es desconocida. Incluso si otros paquicefalosáuridos se golpeaban las cabezas, un tema de discusión continua, la pequeña bóveda de Stygimoloch sugiere que este comportamiento no era importante. En su lugar, el ornamento del cráneo pudo haber actuado durante la exhibición, ser utilizado para la autodefensa, o quizás se trababan y se empujaban en combates intraespecificos, como los cuernos de los ciervos. Sin embargo, es más probable que los cuernos escamosos fueran utilizados para infligir dolor durante el combate golpeándose los flancos." },
      { "titulo": "Clasificación", "informacion": "La especie tipo, S. spinifer, fue descrita por dos paleontólogos de vertebrados, el británico Peter Galton y el alemán Hans-Dieter Sues del Museo Nacional de Historia Natural en 1983. Sin embargo, Jack Horner et al. sospechan que se trata de un ejemplar juvenil de Pachycephalosaurus. El paquicefalosáurido Dracorex es considerado un posible individuo de Stygimoloch o Pachycephalosaurus, ya que no están bien desarrollados la bóveda y los cuernos, posiblemente porque el animal era un juvenil o una hembra. Esta consideración fue apoyada en la reunión anual de 2007 de la Society of Vertebrate Paleontology. Jack Horner de la Universidad de Montana presentó evindencia del único cráneo existente de Dracorex, que este dinosaurio bien puede ser un juvenil de Stygimoloch. Además, presentó datos que indican que ambos Stygimoloch y Dracorex pueden ser forma juveniles de Pachycephalosaurus." },
    ]
  },
  {
    "nombre": "Historia", "contenido": [
      { "titulo": "titulo 1", "informacion": "informacion informacion informacion" },
      { "titulo": "titulo 2", "informacion": "informacion informacion informacion" },
      { "titulo": "titulo 3", "informacion": "informacion informacion informacion" }
    ]
  }
]
